#include "cpu.h"
#include "bus.h"
#include "debug.h"

struct debug debug_output[256] = 
{
  {"BRK", "IMPLIED"}, 
  {"ORA", "(INDIRECT, X)"}, 
  {"JAM", "IMPLIED"}, 
  {"SLO", "(INDIRECT, X)"}, 
  {"NOP", "ZEROPAGE"}, 
  {"ORA", "ZEROPAGE"},  
  {"ASL", "ZEROPAGE"},  
  {"SLO", "ZEROPAGE"},  
  {"PHP", "IMPLIED"},  
  {"ORA", "IMMEDIATE"},  
  {"ASL", "ACCUMULATOR"},  
  {"ANC", "IMMEDIATE"}, 
  {"NOP", "ABSOLUTE"},  
  {"ORA", "ABSOLUTE"},  
  {"ASL", "ABSOLUTE"},  
  {"SLO", "ABSOLUTE"},  
  {"BPL", "RELATIVE"},  
  {"ORA", "(INDIRECT, Y)"},  
  {"JAM", "IMPLIED"},  
  {"SLO", "(INDIRECT, X)"},  
  {"NOP", "ZEROPAGE X"},  
  {"ORA", "ZEROPAGE X"},  
  {"ASL", "ZEROPAGE X"},  
  {"SLO", "ZEROPAGE"},  
  {"CLC", "IMPLIED"},  
  {"ORA", "ABSOLUTE Y"},  
  {"NOP", "IMPLIED"},  
  {"SLO", "ABSOLUTE Y"},  
  {"NOP", "ABSOLUTE X"},  
  {"ORA", "ABSOLUTE X"},  
  {"ASL", "ABSOLUTE X"},  
  {"SLO", "ABSOLUTE X"},  
  {"JSR", "ABSOLUTE"},  
  {"AND", "(INDIRECT, X)"},  
  {"JAM", "IMPLIED"},  
  {"RLA", "(INDIRECT, X)"},  
  {"BIT", "ZEROPAGE"},  
  {"AND", "ZEROPAGE"},  
  {"ROL", "ZEROPAGE"},  
  {"RLA", "ZEROPAGE"},  
  {"PLP", "IMPLIED"},  
  {"AND", "IMMEDIATE"},  
  {"ROL", "ACCUMULATOR"},  
  {"ANC", "IMMEDIATE"}, 
  {"BIT", "ABSOLUTE"},  
  {"AND", "ABSOLUTE"},  
  {"ROL", "ABSOLUTE"},  
  {"RLA", "ABSOLUTE"},  
  {"BMI", "RELATIVE"},  
  {"AND", "(INDIRECT, Y)"},  
  {"JAM", "IMPLIED"},  
  {"RLA", "(INDIRECT, Y)"},  
  {"NOP", "ZEROPAGE X"},  
  {"AND", "ZEROPAGE X"},  
  {"ROL", "ZEROPAGE X"},  
  {"RLA", "ZEROPAGE Y"},  
  {"SEC", "IMPLIED"},  
  {"AND", "ABSOLUTE Y"},  
  {"NOP", "IMPLIED"},  
  {"RLA", "ABSOLUTE Y"}, 
  {"NOP", "ABSOLUTE X"},  
  {"AND", "ABSOLUTE X"},  
  {"ROL", "ABSOLUTE X"},  
  {"RLA", "ABSOLUTE X"},  
  {"RTI", "IMPLIED"},  
  {"EOR", "(INDIRECT, X)"},  
  {"JAM", ""},  
  {"SRE", "(INDIRECT, X)"},  
  {"NOP", "ZEROPAGE"},  
  {"EOR", "ZEROPAGE"},  
  {"LSR", "ZEROPAGE"},  
  {"SRE", "ZEROPAGE"},  
  {"PHA", "IMPLIED"},  
  {"EOR", "IMMEDIATE"},  
  {"LSR", "ACCUMULATOR"},  
  {"ALR", "IMMEDIATE"}, 
  {"JMP", "ABSOLUTE"},  
  {"EOR", "ABSOLUTE"},  
  {"LSR", "ABSOLUTE"},  
  {"SRE", "ABSOLUTE"},  
  {"BVC", "RELATIVE"},  
  {"EOR", "(INDIRECT, Y)"},  
  {"JAM", ""},  
  {"SRE", "(INDIRECT, Y)"},  
  {"NOP", "ZEROPAGE X"},  
  {"EOR", "ZEROPAGE X"},  
  {"LSR", "ZEROPAGE X"},  
  {"SRE", "ZEROPAGE X"},  
  {"CLI", "IMPLIED"},  
  {"EOR", "ABSOLUTE Y"},  
  {"NOP", "IMPLIED"},  
  {"SRE", "ABSOLUTE Y"}, 
  {"NOP", "ABSOLUTE X"},  
  {"EOR", "ABSOLUTE X"},  
  {"LSR", "ABSOLUTE X"},  
  {"SRE", "ABSOLUTE X"},  
  {"RTS", "IMPLIED"},  
  {"ADC", "(INDIRECT, X)"},  
  {"JAM", "IMPLIED"},  
  {"RRA", "(INDIRECT, X)"},  
  {"NOP", "ZEROPAGE"},  
  {"ADC", "ZEROPAGE"},  
  {"ROR", "ZEROPAGE"},  
  {"RRA", "ZEROPAGE"},  
  {"PLA", "IMPLIED"},  
  {"ADC", "IMMEDIATE"},  
  {"ROR", "ACCUMULATOR"},  
  {"ARR", "IMMEDIATE"}, 
  {"JMP", "INDIRECT"},  
  {"ADC", "ABSOLUTE"},  
  {"ROR", "ABSOLUTE"},  
  {"RRA", "ABSOLUTE X"},  
  {"BVS", "RELATIVE"},  
  {"ADC", "(INDIRECT, Y)"},  
  {"JAM", ""},  
  {"RRA", "(INDIRECT, Y)"},  
  {"NOP", "ZEROPAGE X"},  
  {"ADC", "ZEROPAGE X"},  
  {"ROR", "ZEROPAGE X"},  
  {"RRA", "ZEROPAGE X"},  
  {"SEI", "IMPLIED"},  
  {"ADC", "ABSOLUTE Y"},  
  {"NOP", "IMPLIED"},  
  {"RRA", "ABSOLUTE Y"},  
  {"NOP", "ABSOLUTE X"},  
  {"ADC", "ABSOLUTE X"},  
  {"ROR", "ABSOLUTE X"},  
  {"RRA", "ABSOLUTE X"},   
  {"NOP", "IMMEDIATE"},  
  {"STA", "(INDIRECT, X)"},  
  {"NOP", "IMMEDIATE"},  
  {"SAX", "(INDIRECT, X)"},  
  {"STY", "ZEROPAGE"},  
  {"STA", "ZEROPAGE"},  
  {"STX", "ZEROPAGE"},  
  {"SAX", "ZEROPAGE"},  
  {"DEY", "IMPLIED"},  
  {"NOP", "IMPLIED"},  
  {"TXA", "IMPLIED"}, 
  {"XAA", "IMMEDIATE"},  
  {"STY", "ABSOLUTE"},  
  {"STA", "ABSOLUTE"},  
  {"STX", "ABSOLUTE"},  
  {"SAX", "ABSOLUTE"},  
  {"BCC", "RELATIVE"},  
  {"STA", "(INDIRECT, Y)"},  
  {"JAM", "IMPLIED"},  
  {"AHX", "(INDIRECT, Y)"},  
  {"STY", "ZEROPAGE"},  
  {"STA", "ZEROPAGE"},  
  {"STX", "ZEROPAGE"},  
  {"SAX", "ZEROPAGE Y"},  
  {"TYA", "IMPLIED"},  
  {"STA", "ABSOLUTE Y"},  
  {"TXS", "IMPLIED"},  
  {"TAS", "ABSOLUTE Y"},  
  {"SHY", "ABSOLUTE X"}, 
  {"STA", "ABSOLUTE X"},  
  {"SHX", "ABSOLUTE Y"},  
  {"AHX", "ABSOLUTE Y"},   
  {"LDY", "IMMEDIATE"},  
  {"LDA", "(INDIRECT, X)"},  
  {"LDX", "IMMEDIATE"}, 
  {"LAX", "(INDIRECT, X)"},  
  {"LDY", "ZEROPAGE"}, 
  {"LDA", "ZEROPAGE"},  
  {"LDX", "ZEROPAGE"},  
  {"LAX", "ZEROPAGE"},  
  {"TAY", "IMPLIED"},  
  {"LDA", "IMMEDIATE"},  
  {"TAX", "IMPLIED"},  
  {"LAX", "IMMEDIATE"},  
  {"LDY", "ABSOLUTE"},  
  {"LDA", "ABSOLUTE"},  
  {"LDX", "ABSOLUTE"},  
  {"LAX", "ABSOLUTE"},  
  {"BCS", "RELATIVE"}, 
  {"LDA", "(INDIRECT, Y)"},  
  {"JAM", "IMPLIED"}, 
  {"LAX", "(INDIRECT, Y)"},  
  {"LDY", "ZEROPAGE X"}, 
  {"LDA", "ZEROPAGE X"}, 
  {"LDX", "ZEROPAGE Y"}, 
  {"LAX", "ZEROPAGE Y"}, 
  {"CLV", "IMPLIED"}, 
  {"LDA", "ABSOLUTE Y"}, 
  {"TSX", "IMPLIED"},  
  {"LAS", "ABSOLUTE Y"},  
  {"LDY", "ABSOLUTE X"},  
  {"LDA", "ABSOLUTE X"},  
  {"LDX", "ABSOLUTE Y"},  
  {"LAX", "ABSOLUTE Y"},   
  {"CPY", "IMMEDIATE"},  
  {"CMP", "(INDIRECT, X)"},  
  {"NOP", "IMMEDIATE"}, 
  {"DCP", "(INDIRECT, X)"},  
  {"CPY", "ZEROPAGE"}, 
  {"CMP", "ZEROPAGE"}, 
  {"DEC", "ZEROPAGE"}, 
  {"DCP", "ZEROPAGE"}, 
  {"INY", "IMPLIED"}, 
  {"CMP", "IMMEDIATE"}, 
  {"DEX", "IMPLIED"},
  {"AXS", "IMMEDIATE"}, 
  {"CPY", "ABSOLUTE"}, 
  {"CMP", "ABSOLUTE"}, 
  {"DEC", "ABSOLUTE"}, 
  {"DCP", "ABSOLUTE X"}, 
  {"BNE", "RELATIVE"}, 
  {"CMP", "(INDIRECT, Y)"}, 
  {"JAM", "IMPLIED"}, 
  {"DCP", "(INDIRECT, Y)"}, 
  {"NOP", "ZEROPAGE X"}, 
  {"CMP", "ZEROPAGE X"}, 
  {"DEC", "ZEROPAGE X"}, 
  {"DCP", "ZEROPAGE X"}, 
  {"CLD", "IMPLIED"}, 
  {"CMP", "ABSOLUTE Y"}, 
  {"NOP", "IMPLIED"}, 
  {"DCP", "ABSOLUTE Y"}, 
  {"NOP", "ABSOLUTE X"}, 
  {"CMP", "ABSOLUTE X"}, 
  {"DEC", "ABSOLUTE X"}, 
  {"DCP", "ABSOLUTE X"},  
  {"CPX", "IMMEDIATE"}, 
  {"SBC", "(INDIRECT, X)"}, 
  {"NOP", "IMMEDIATE"}, 
  {"ISC", "(INDIRECT, X)"}, 
  {"CPX", "ZEROPAGE"}, 
  {"SBC", "ZEROPAGE"}, 
  {"INC", "ZEROPAGE"}, 
  {"ISC", "ZEROPAGE"}, 
  {"INX", "IMPLIED"}, 
  {"SBC", "IMMEDIATE"}, 
  {"NOP", "IMPLIED"}, 
  {"SBC", "IMMEDIATE"}, 
  {"CPX", "ABSOLUTE"}, 
  {"SBC", "ABSOLUTE"},  
  {"INC", "ABSOLUTE"}, 
  {"ISC", "ABSOLUTE"}, 
  {"BEQ", "RELATIVE"}, 
  {"SBC", "(INDIRECT, Y)"}, 
  {"JAM", "IMPLIED"}, 
  {"ISC", "(INDIRECT, Y)"}, 
  {"NOP", "ZEROPAGE X"}, 
  {"SBC", "ZEROPAGE X"}, 
  {"INC", "ZEROPAGE X"}, 
  {"ISC", "ZEROPAGE X"}, 
  {"SED", "IMPLIED"}, 
  {"SBC", "ABSOLUTE Y"}, 
  {"NOP", "IMPLIED"}, 
  {"ISC", "ABSOLUTE Y"}, 
  {"NOP", "ABSOLUTE X"}, 
  {"SBC", "ABSOLUTE X"}, 
  {"INC", "ABSOLUTE X"}, 
  {"ISC", "ABSOLUTE X"},  
};


void
cpu_debug(MOS_6510* const c)
{
  uint8_t opcode = rb(c, c->pc);

  char flags[] = "........";

  if(c->nf) flags[0] = 'N';
  if(c->vf) flags[1] = 'V';
  flags[2] = 'U'; // Must always be one
  if(c->bf) flags[3] = 'B';
  if(c->df) flags[4] = 'D';
  if(c->idf) flags[5] = 'I';
  if(c->zf) flags[6] = 'Z';
  if(c->cf) flags[7] = 'C';

  /* INSTRUCTIONS, ADDRESSING MODES AND REGISTERS */

/*  
  printf("[0x%04X] [%02X] %s, [%s]\t", c->pc, rb(c, c->pc), debug_output[opcode].mnemonics, debug_output[opcode].address_mode);

  printf("A: %02X X: %02X Y: %02X SP: %02X P: %02X [%s] CYC: %llu\n", 
      c->a,
      c->x,
      c->y,
      c->sp,
      get_flags(c),
      flags,
      c->cyc);
*/
  printf("[%d] [%d] %s, [%s]\t", c->pc, rb(c, c->pc), debug_output[opcode].mnemonics, debug_output[opcode].address_mode);

  printf("A: %d X: %d Y: %d SP: %d P: %d [%s] CYC: %llu\n", 
      c->a,
      c->x,
      c->y,
      c->sp,
      get_flags(c),
      flags,
      c->cyc);
}
